In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

all_data = pd.read_csv('sales所在周次节假日_剔除换货.csv')
all_data.rename(columns={'店铺名称':'store','地理位置指数':'position','年份':'years','周次':'weeks','是否包含法定节假日':'Isholiday','季节':'season','大类':'item','销量(剔除换货）':'sales','均价（剔除换货）':'prices','促销（剔除换货）':'discount'},inplace=True)
all_data.shape

(18163, 10)

In [12]:
a = all_data
week_5 = a.loc[lambda a : a['years'] == 2015]
week_6 = a.loc[lambda a : a['years'] == 2016]
week_6['weeks'] += 53
a = pd.concat([week_5,week_6])
a

/home/lin/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


store  position  years  weeks  Isholiday season item  sales  \
0        深圳前进天虹         7   2015      1          1     冬季   中靴      1   
1        深圳前进天虹         7   2015      1          1     冬季   低靴     30   
2        深圳前进天虹         7   2015      1          1     冬季   长靴      2   
3        深圳前进天虹         7   2015      1          1     冬季   高靴      2   
4        深圳前进天虹         7   2015      1          1     春季   浅口      1   
5        深圳前进天虹         7   2015      1          1     秋季   深口      2   
6        深圳前进天虹         7   2015      2          0     冬季   中靴      1   
7        深圳前进天虹         7   2015      2          0     冬季   低靴      6   
8        深圳前进天虹         7   2015      2          0     春季   浅口      1   
9        深圳前进天虹         7   2015      2          0     秋季   浅口      2   
10       深圳前进天虹         7   2015      2          0     秋季   深口      3   
11       深圳前进天虹         7   2015      3          0     冬季   中靴      1   
12       深圳前进天虹         7   2015      3          0     冬季   低靴      8   
13       深圳前进天虹         7   2015      3          0     冬季   高靴      2   
14       深圳前进天虹         7   2015      3          0     春季   浅口      3   
15       深圳前进天虹         7   2015      3          0     秋季   浅口      1   
16       深圳前进天虹         7   2015      3          0     秋季   深口      1   
17       深圳前进天虹         7   2015      4          0     冬季   低靴     19   
18       深圳前进天虹         7   2015      4          0     冬季   高靴      1   
19       深圳前进天虹         7   2015      4          0     春季   浅口      4   
20       深圳前进天虹         7   2015      4          0     秋季   浅口      2   
21       深圳前进天虹         7   2015      4          0     秋季   深口      3   
22       深圳前进天虹         7   2015      5          0     冬季   低靴     16   
23       深圳前进天虹         7   2015      5          0     冬季   高靴      1   
24       深圳前进天虹         7   2015      5          0     春季   浅口      3   
25       深圳前进天虹         7   2015      5          0     秋季   浅口      2   
26       深圳前进天虹         7   2015      5          0     秋季   深口      4   
27       深圳前进天虹         7   2015      6          0     冬季   中靴      1   
28       深圳前进天虹         7   2015      6          0     冬季   低靴     30   
29       深圳前进天虹         7   2015      6          0     春季   浅口      1   
...         ...       ...    ...    ...        ...    ...  ...    ...   
18133  深圳龙岗龙新天虹         7   2016    102          0     冬季   高靴      6   
18134  深圳龙岗龙新天虹         7   2016    102          0     春季   浅口     44   
18135  深圳龙岗龙新天虹         7   2016    102          0     春季   深口      5   
18136  深圳龙岗龙新天虹         7   2016    102          0     秋季   浅口     12   
18137  深圳龙岗龙新天虹         7   2016    102          0     秋季   深口     36   
18138  深圳龙岗龙新天虹         7   2016    103          0     冬季   中靴      1   
18139  深圳龙岗龙新天虹         7   2016    103          0     冬季   低靴      7   
18140  深圳龙岗龙新天虹         7   2016    103          0     冬季   裸靴      6   
18141  深圳龙岗龙新天虹         7   2016    103          0     春季   浅口     12   
18142  深圳龙岗龙新天虹         7   2016    103          0     秋季   浅口      3   
18143  深圳龙岗龙新天虹         7   2016    103          0     秋季   深口      3   
18144  深圳龙岗龙新天虹         7   2016    104          0     冬季   低靴      5   
18145  深圳龙岗龙新天虹         7   2016    104          0     冬季   裸靴      2   
18146  深圳龙岗龙新天虹         7   2016    104          0     春季   浅口      5   
18147  深圳龙岗龙新天虹         7   2016    104          0     秋季   浅口      3   
18148  深圳龙岗龙新天虹         7   2016    104          0     秋季   深口      1   
18149  深圳龙岗龙新天虹         7   2016    105          0     冬季   中靴      1   
18150  深圳龙岗龙新天虹         7   2016    105          0     冬季   低靴     12   
18151  深圳龙岗龙新天虹         7   2016    105          0     冬季   裸靴      4   
18152  深圳龙岗龙新天虹         7   2016    105          0     冬季   长靴      1   
18153  深圳龙岗龙新天虹         7   2016    105          0     春季   浅口      9   
18154  深圳龙岗龙新天虹         7   2016    105          0     秋季   浅口      1   
18155  深圳龙岗龙新天虹         7   2016    105          0     秋季   深口     1

In [13]:
a_part = a.loc[:,['store','weeks','item','sales']]

In [14]:
a_part = a.loc[:,['store','weeks','item','sales']]

In [15]:
from sklearn import preprocessing

#map店铺名称
name = a['store']
le = preprocessing.LabelEncoder()
le.fit(name)
list(name)
le.transform(name)
tmp = le.transform(name)
a['store'] = tmp

#map合并大类
category = a['item']
le.fit(category)
list(category)
le.transform(category)
tmp = le.transform(category)
a['item'] = tmp
a

store  position  years  weeks  Isholiday season  item  sales  \
0          0         7   2015      1          1     冬季     1      1   
1          0         7   2015      1          1     冬季     2     30   
2          0         7   2015      1          1     冬季     9      2   
3          0         7   2015      1          1     冬季    10      2   
4          0         7   2015      1          1     春季     6      1   
5          0         7   2015      1          1     秋季     7      2   
6          0         7   2015      2          0     冬季     1      1   
7          0         7   2015      2          0     冬季     2      6   
8          0         7   2015      2          0     春季     6      1   
9          0         7   2015      2          0     秋季     6      2   
10         0         7   2015      2          0     秋季     7      3   
11         0         7   2015      3          0     冬季     1      1   
12         0         7   2015      3          0     冬季     2      8   
13         0         7   2015      3          0     冬季    10      2   
14         0         7   2015      3          0     春季     6      3   
15         0         7   2015      3          0     秋季     6      1   
16         0         7   2015      3          0     秋季     7      1   
17         0         7   2015      4          0     冬季     2     19   
18         0         7   2015      4          0     冬季    10      1   
19         0         7   2015      4          0     春季     6      4   
20         0         7   2015      4          0     秋季     6      2   
21         0         7   2015      4          0     秋季     7      3   
22         0         7   2015      5          0     冬季     2     16   
23         0         7   2015      5          0     冬季    10      1   
24         0         7   2015      5          0     春季     6      3   
25         0         7   2015      5          0     秋季     6      2   
26         0         7   2015      5          0     秋季     7      4   
27         0         7   2015      6          0     冬季     1      1   
28         0         7   2015      6          0     冬季     2     30   
29         0         7   2015      6          0     春季     6      1   
...      ...       ...    ...    ...        ...    ...   ...    ...   
18133     29         7   2016    102          0     冬季    10      6   
18134     29         7   2016    102          0     春季     6     44   
18135     29         7   2016    102          0     春季     7      5   
18136     29         7   2016    102          0     秋季     6     12   
18137     29         7   2016    102          0     秋季     7     36   
18138     29         7   2016    103          0     冬季     1      1   
18139     29         7   2016    103          0     冬季     2      7   
18140     29         7   2016    103          0     冬季     8      6   
18141     29         7   2016    103          0     春季     6     12   
18142     29         7   2016    103          0     秋季     6      3   
18143     29         7   2016    103          0     秋季     7      3   
18144     29         7   2016    104          0     冬季     2      5   
18145     29         7   2016    104          0     冬季     8      2   
18146     29         7   2016    104          0     春季     6      5   
18147     29         7   2016    104          0     秋季     6      3   
18148     29         7   2016    104          0     秋季     7      1   
18149     29         7   2016    105          0     冬季     1      1   
18150     29         7   2016    105          0     冬季     2     12   
18151     29         7   2016    105          0     冬季     8      4   
18152     29         7   2016    105          0     冬季     9      1   
18153     29         7   2016    105          0     春季     6      9   
18154     29         7   2016    105          0     秋季     6      1   
18155     29         7   2016    105          0     秋季     7     12   
18156     29         7   2016    106          0     冬季     1      4   
18157     29         7   2016  

In [16]:
a_part = a.loc[:,['store','weeks','item','sales']]
a_part.describe()

store         weeks         item         sales
count  18163.000000  18163.000000  18163.00000  18163.000000
mean      14.547156     56.961295      5.41992      7.880031
std        8.695615     30.663260      2.71015     16.436671
min        0.000000      1.000000      0.00000      1.000000
25%        7.000000     31.000000      3.00000      2.000000
50%       14.000000     59.000000      6.00000      4.000000
75%       22.000000     84.000000      7.00000      9.000000
max       29.000000    106.000000     11.00000    912.000000

In [17]:
tmp = np.zeros((30,1272),dtype=int)
for i in range(30):
    tmp[i] = np.full((1272,),i)
    print(tmp[i])
    
    gen_store=np.concatenate((tmp[i]),axis = None)
    
tmp.shape
gen_store=np.concatenate((tmp),axis = None)
gen_store.shape

[0 0 0 ... 0 0 0]
[1 1 1 ... 1 1 1]
[2 2 2 ... 2 2 2]
[3 3 3 ... 3 3 3]
[4 4 4 ... 4 4 4]
[5 5 5 ... 5 5 5]
[6 6 6 ... 6 6 6]
[7 7 7 ... 7 7 7]
[8 8 8 ... 8 8 8]
[9 9 9 ... 9 9 9]
[10 10 10 ... 10 10 10]
[11 11 11 ... 11 11 11]
[12 12 12 ... 12 12 12]
[13 13 13 ... 13 13 13]
[14 14 14 ... 14 14 14]
[15 15 15 ... 15 15 15]
[16 16 16 ... 16 16 16]
[17 17 17 ... 17 17 17]
[18 18 18 ... 18 18 18]
[19 19 19 ... 19 19 19]
[20 20 20 ... 20 20 20]
[21 21 21 ... 21 21 21]
[22 22 22 ... 22 22 22]
[23 23 23 ... 23 23 23]
[24 24 24 ... 24 24 24]
[25 25 25 ... 25 25 25]
[26 26 26 ... 26 26 26]
[27 27 27 ... 27 27 27]
[28 28 28 ... 28 28 28]
[29 29 29 ... 29 29 29]


(38160,)

In [35]:

tmp = np.zeros((30,106,12),dtype=int)
for i in range(30):
    for j in range(1, 106):
        tmp[i][j] = np.full((12),j)
        #print(tmp[i][j])

gen_week = np.concatenate((tmp),axis=None)
gen_week.shape
#gen_week = pd.DataFrame(gen_week)

(38160,)

In [47]:
tmp = np.zeros((12,3180),dtype=int)
for i in range(12):
    tmp[i] = np.full((3180),i)
    print(tmp[i])

np.reshape(tmp,11,order='F')
#gen_item = np.concatenate((tmp),axis=0)
#gen_item

[0 0 0 ... 0 0 0]
[1 1 1 ... 1 1 1]
[2 2 2 ... 2 2 2]
[3 3 3 ... 3 3 3]
[4 4 4 ... 4 4 4]
[5 5 5 ... 5 5 5]
[6 6 6 ... 6 6 6]
[7 7 7 ... 7 7 7]
[8 8 8 ... 8 8 8]
[9 9 9 ... 9 9 9]
[10 10 10 ... 10 10 10]
[11 11 11 ... 11 11 11]


ValueError: cannot reshape array of size 38160 into shape (11,)

In [31]:
gen_week.drop['0' == 0]

TypeError: 'method' object is not subscriptable

In [9]:
a_gen = np.zeros((38160,4),dtype=int)


In [10]:
df = pd.DataFrame({'store':range(29),
                  'weeks':range(1, 106),
                  'item':range(11),
                  'sales':range(0)})
df

ValueError: arrays must all be same length

In [ ]:
count = 1
for i in range(29):
    for j in range(106):
        print(j)
        count += 1
        print(count)
        
        

In [ ]:
list_item = a['item']

In [ ]:
list_store = a['store']

In [ ]:
list_item

In [ ]:
list_store

In [ ]:
count = 0
for i in list_store:
    for j in list_item:
        print(i,j)
        count += 1
        print(count)
        