In [1]:
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt

all_data = pd.read_csv('sales所在周次节假日_剔除换货.csv')
all_data.rename(columns={'店铺名称':'store','地理位置指数':'position','年份':'years','周次':'weeks','是否包含法定节假日':'Isholiday','季节':'season','大类':'item','销量(剔除换货）':'sales','均价（剔除换货）':'prices','促销（剔除换货）':'discount'},inplace=True)
all_data.shape

(18163, 10)

In [2]:
a = all_data
week_5 = a.loc[lambda a : a['years'] == 2015]
week_6 = a.loc[lambda a : a['years'] == 2016]
week_6['weeks'] += 53
a = pd.concat([week_5,week_6])
a

/home/lin/anaconda3/envs/boost/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


store  position  years  weeks  Isholiday season item  sales  \
0        深圳前进天虹         7   2015      1          1     冬季   中靴      1   
1        深圳前进天虹         7   2015      1          1     冬季   低靴     30   
2        深圳前进天虹         7   2015      1          1     冬季   长靴      2   
3        深圳前进天虹         7   2015      1          1     冬季   高靴      2   
4        深圳前进天虹         7   2015      1          1     春季   浅口      1   
5        深圳前进天虹         7   2015      1          1     秋季   深口      2   
6        深圳前进天虹         7   2015      2          0     冬季   中靴      1   
7        深圳前进天虹         7   2015      2          0     冬季   低靴      6   
8        深圳前进天虹         7   2015      2          0     春季   浅口      1   
9        深圳前进天虹         7   2015      2          0     秋季   浅口      2   
10       深圳前进天虹         7   2015      2          0     秋季   深口      3   
11       深圳前进天虹         7   2015      3          0     冬季   中靴      1   
12       深圳前进天虹         7   2015      3          0     冬季   低靴      8   
13       深圳前进天虹         7   2015      3          0     冬季   高靴      2   
14       深圳前进天虹         7   2015      3          0     春季   浅口      3   
15       深圳前进天虹         7   2015      3          0     秋季   浅口      1   
16       深圳前进天虹         7   2015      3          0     秋季   深口      1   
17       深圳前进天虹         7   2015      4          0     冬季   低靴     19   
18       深圳前进天虹         7   2015      4          0     冬季   高靴      1   
19       深圳前进天虹         7   2015      4          0     春季   浅口      4   
20       深圳前进天虹         7   2015      4          0     秋季   浅口      2   
21       深圳前进天虹         7   2015      4          0     秋季   深口      3   
22       深圳前进天虹         7   2015      5          0     冬季   低靴     16   
23       深圳前进天虹         7   2015      5          0     冬季   高靴      1   
24       深圳前进天虹         7   2015      5          0     春季   浅口      3   
25       深圳前进天虹         7   2015      5          0     秋季   浅口      2   
26       深圳前进天虹         7   2015      5          0     秋季   深口      4   
27       深圳前进天虹         7   2015      6          0     冬季   中靴      1   
28       深圳前进天虹         7   2015      6          0     冬季   低靴     30   
29       深圳前进天虹         7   2015      6          0     春季   浅口      1   
...         ...       ...    ...    ...        ...    ...  ...    ...   
18133  深圳龙岗龙新天虹         7   2016    102          0     冬季   高靴      6   
18134  深圳龙岗龙新天虹         7   2016    102          0     春季   浅口     44   
18135  深圳龙岗龙新天虹         7   2016    102          0     春季   深口      5   
18136  深圳龙岗龙新天虹         7   2016    102          0     秋季   浅口     12   
18137  深圳龙岗龙新天虹         7   2016    102          0     秋季   深口     36   
18138  深圳龙岗龙新天虹         7   2016    103          0     冬季   中靴      1   
18139  深圳龙岗龙新天虹         7   2016    103          0     冬季   低靴      7   
18140  深圳龙岗龙新天虹         7   2016    103          0     冬季   裸靴      6   
18141  深圳龙岗龙新天虹         7   2016    103          0     春季   浅口     12   
18142  深圳龙岗龙新天虹         7   2016    103          0     秋季   浅口      3   
18143  深圳龙岗龙新天虹         7   2016    103          0     秋季   深口      3   
18144  深圳龙岗龙新天虹         7   2016    104          0     冬季   低靴      5   
18145  深圳龙岗龙新天虹         7   2016    104          0     冬季   裸靴      2   
18146  深圳龙岗龙新天虹         7   2016    104          0     春季   浅口      5   
18147  深圳龙岗龙新天虹         7   2016    104          0     秋季   浅口      3   
18148  深圳龙岗龙新天虹         7   2016    104          0     秋季   深口      1   
18149  深圳龙岗龙新天虹         7   2016    105          0     冬季   中靴      1   
18150  深圳龙岗龙新天虹         7   2016    105          0     冬季   低靴     12   
18151  深圳龙岗龙新天虹         7   2016    105          0     冬季   裸靴      4   
18152  深圳龙岗龙新天虹         7   2016    105          0     冬季   长靴      1   
18153  深圳龙岗龙新天虹         7   2016    105          0     春季   浅口      9   
18154  深圳龙岗龙新天虹         7   2016    105          0     秋季   浅口      1   
18155  深圳龙岗龙新天虹         7   2016    105          0     秋季   深口     1

In [3]:
a_part = a.loc[:,['store','weeks','item','sales']]

In [4]:
a_part = a.loc[:,['store','weeks','item','sales']]

In [5]:
from sklearn import preprocessing

#map店铺名称
name = a['store']
le = preprocessing.LabelEncoder()
le.fit(name)
list(name)
le.transform(name)
tmp = le.transform(name)
a['store'] = tmp

#map合并大类
category = a['item']
le.fit(category)
list(category)
le.transform(category)
tmp = le.transform(category)
a['item'] = tmp
a

store  position  years  weeks  Isholiday season  item  sales  \
0          0         7   2015      1          1     冬季     1      1   
1          0         7   2015      1          1     冬季     2     30   
2          0         7   2015      1          1     冬季     9      2   
3          0         7   2015      1          1     冬季    10      2   
4          0         7   2015      1          1     春季     6      1   
5          0         7   2015      1          1     秋季     7      2   
6          0         7   2015      2          0     冬季     1      1   
7          0         7   2015      2          0     冬季     2      6   
8          0         7   2015      2          0     春季     6      1   
9          0         7   2015      2          0     秋季     6      2   
10         0         7   2015      2          0     秋季     7      3   
11         0         7   2015      3          0     冬季     1      1   
12         0         7   2015      3          0     冬季     2      8   
13         0         7   2015      3          0     冬季    10      2   
14         0         7   2015      3          0     春季     6      3   
15         0         7   2015      3          0     秋季     6      1   
16         0         7   2015      3          0     秋季     7      1   
17         0         7   2015      4          0     冬季     2     19   
18         0         7   2015      4          0     冬季    10      1   
19         0         7   2015      4          0     春季     6      4   
20         0         7   2015      4          0     秋季     6      2   
21         0         7   2015      4          0     秋季     7      3   
22         0         7   2015      5          0     冬季     2     16   
23         0         7   2015      5          0     冬季    10      1   
24         0         7   2015      5          0     春季     6      3   
25         0         7   2015      5          0     秋季     6      2   
26         0         7   2015      5          0     秋季     7      4   
27         0         7   2015      6          0     冬季     1      1   
28         0         7   2015      6          0     冬季     2     30   
29         0         7   2015      6          0     春季     6      1   
...      ...       ...    ...    ...        ...    ...   ...    ...   
18133     29         7   2016    102          0     冬季    10      6   
18134     29         7   2016    102          0     春季     6     44   
18135     29         7   2016    102          0     春季     7      5   
18136     29         7   2016    102          0     秋季     6     12   
18137     29         7   2016    102          0     秋季     7     36   
18138     29         7   2016    103          0     冬季     1      1   
18139     29         7   2016    103          0     冬季     2      7   
18140     29         7   2016    103          0     冬季     8      6   
18141     29         7   2016    103          0     春季     6     12   
18142     29         7   2016    103          0     秋季     6      3   
18143     29         7   2016    103          0     秋季     7      3   
18144     29         7   2016    104          0     冬季     2      5   
18145     29         7   2016    104          0     冬季     8      2   
18146     29         7   2016    104          0     春季     6      5   
18147     29         7   2016    104          0     秋季     6      3   
18148     29         7   2016    104          0     秋季     7      1   
18149     29         7   2016    105          0     冬季     1      1   
18150     29         7   2016    105          0     冬季     2     12   
18151     29         7   2016    105          0     冬季     8      4   
18152     29         7   2016    105          0     冬季     9      1   
18153     29         7   2016    105          0     春季     6      9   
18154     29         7   2016    105          0     秋季     6      1   
18155     29         7   2016    105          0     秋季     7     12   
18156     29         7   2016    106          0     冬季     1      4   
18157     29         7   2016  

In [6]:
a_part = a.loc[:,['store','weeks','item','sales']]
a_part.describe()

store         weeks         item         sales
count  18163.000000  18163.000000  18163.00000  18163.000000
mean      14.547156     56.961295      5.41992      7.880031
std        8.695615     30.663260      2.71015     16.436671
min        0.000000      1.000000      0.00000      1.000000
25%        7.000000     31.000000      3.00000      2.000000
50%       14.000000     59.000000      6.00000      4.000000
75%       22.000000     84.000000      7.00000      9.000000
max       29.000000    106.000000     11.00000    912.000000

In [7]:
tmp = np.zeros((30,1272),dtype=int)
for i in range(30):
    tmp[i] = np.full((1272,),i)
    print(tmp[i])
    
    gen_store=np.concatenate((tmp[i]),axis = None)
    
tmp.shape
gen_store=np.concatenate((tmp),axis = None)
gen_store.shape

[0 0 0 ... 0 0 0]
[1 1 1 ... 1 1 1]
[2 2 2 ... 2 2 2]
[3 3 3 ... 3 3 3]
[4 4 4 ... 4 4 4]
[5 5 5 ... 5 5 5]
[6 6 6 ... 6 6 6]
[7 7 7 ... 7 7 7]
[8 8 8 ... 8 8 8]
[9 9 9 ... 9 9 9]
[10 10 10 ... 10 10 10]
[11 11 11 ... 11 11 11]
[12 12 12 ... 12 12 12]
[13 13 13 ... 13 13 13]
[14 14 14 ... 14 14 14]
[15 15 15 ... 15 15 15]
[16 16 16 ... 16 16 16]
[17 17 17 ... 17 17 17]
[18 18 18 ... 18 18 18]
[19 19 19 ... 19 19 19]
[20 20 20 ... 20 20 20]
[21 21 21 ... 21 21 21]
[22 22 22 ... 22 22 22]
[23 23 23 ... 23 23 23]
[24 24 24 ... 24 24 24]
[25 25 25 ... 25 25 25]
[26 26 26 ... 26 26 26]
[27 27 27 ... 27 27 27]
[28 28 28 ... 28 28 28]
[29 29 29 ... 29 29 29]


(38160,)

In [8]:

tmp = np.zeros((30,106,12),dtype=int)
for i in range(30):
    for j in range(1, 106):
        tmp[i][j] = np.full((12),j)
        #print(tmp[i][j])

gen_week = np.concatenate((tmp),axis=None)
gen_week.shape
#gen_week = pd.DataFrame(gen_week)

(38160,)

In [9]:
tmp = np.zeros((12,3180),dtype=int)
for i in range(12):
    tmp[i] = np.full((3180),i)
    print(tmp[i])

gen_item = np.reshape(tmp,38160,order='F')
#gen_item = np.concatenate((tmp),axis=0)
gen_item.shape

[0 0 0 ... 0 0 0]
[1 1 1 ... 1 1 1]
[2 2 2 ... 2 2 2]
[3 3 3 ... 3 3 3]
[4 4 4 ... 4 4 4]
[5 5 5 ... 5 5 5]
[6 6 6 ... 6 6 6]
[7 7 7 ... 7 7 7]
[8 8 8 ... 8 8 8]
[9 9 9 ... 9 9 9]
[10 10 10 ... 10 10 10]
[11 11 11 ... 11 11 11]


(38160,)

In [10]:
gen_sales = np.zeros((38160),dtype=int)
gen_sales.shape

(38160,)

In [11]:
df = pd.DataFrame({'store':gen_store,
                  'weeks':gen_week,
                  'item':gen_item,
                  'sales':gen_sales})
df

store  weeks  item  sales
0          0      0     0      0
1          0      0     1      0
2          0      0     2      0
3          0      0     3      0
4          0      0     4      0
5          0      0     5      0
6          0      0     6      0
7          0      0     7      0
8          0      0     8      0
9          0      0     9      0
10         0      0    10      0
11         0      0    11      0
12         0      1     0      0
13         0      1     1      0
14         0      1     2      0
15         0      1     3      0
16         0      1     4      0
17         0      1     5      0
18         0      1     6      0
19         0      1     7      0
20         0      1     8      0
21         0      1     9      0
22         0      1    10      0
23         0      1    11      0
24         0      2     0      0
25         0      2     1      0
26         0      2     2      0
27         0      2     3      0
28         0      2     4      0
29         0      2     5      0
...      ...    ...   ...    ...
38130     29    103     6      0
38131     29    103     7      0
38132     29    103     8      0
38133     29    103     9      0
38134     29    103    10      0
38135     29    103    11      0
38136     29    104     0      0
38137     29    104     1      0
38138     29    104     2      0
38139     29    104     3      0
38140     29    104     4      0
38141     29    104     5      0
38142     29    104     6      0
38143     29    104     7      0
38144     29    104     8      0
38145     29    104     9      0
38146     29    104    10      0
38147     29    104    11      0
38148     29    105     0      0
38149     29    105     1      0
38150     29    105     2      0
38151     29    105     3      0
38152     29    105     4      0
38153     29    105     5      0
38154     29    105     6      0
38155     29    105     7      0
38156     29    105     8      0
38157     29    105     9      0
38158     29    105    10      0
38159     29    105    11      0

[38160 rows x 4 columns]

In [12]:
a_part['weeks'] -= 1
a_part

store  weeks  item  sales
0          0      0     1      1
1          0      0     2     30
2          0      0     9      2
3          0      0    10      2
4          0      0     6      1
5          0      0     7      2
6          0      1     1      1
7          0      1     2      6
8          0      1     6      1
9          0      1     6      2
10         0      1     7      3
11         0      2     1      1
12         0      2     2      8
13         0      2    10      2
14         0      2     6      3
15         0      2     6      1
16         0      2     7      1
17         0      3     2     19
18         0      3    10      1
19         0      3     6      4
20         0      3     6      2
21         0      3     7      3
22         0      4     2     16
23         0      4    10      1
24         0      4     6      3
25         0      4     6      2
26         0      4     7      4
27         0      5     1      1
28         0      5     2     30
29         0      5     6      1
...      ...    ...   ...    ...
18133     29    101    10      6
18134     29    101     6     44
18135     29    101     7      5
18136     29    101     6     12
18137     29    101     7     36
18138     29    102     1      1
18139     29    102     2      7
18140     29    102     8      6
18141     29    102     6     12
18142     29    102     6      3
18143     29    102     7      3
18144     29    103     2      5
18145     29    103     8      2
18146     29    103     6      5
18147     29    103     6      3
18148     29    103     7      1
18149     29    104     1      1
18150     29    104     2     12
18151     29    104     8      4
18152     29    104     9      1
18153     29    104     6      9
18154     29    104     6      1
18155     29    104     7     12
18156     29    105     1      4
18157     29    105     2     23
18158     29    105     7      1
18159     29    105     9      2
18160     29    105     6      2
18161     29    105     6      4
18162     29    105     7      9

[18163 rows x 4 columns]

In [13]:
a_part

store  weeks  item  sales
0          0      0     1      1
1          0      0     2     30
2          0      0     9      2
3          0      0    10      2
4          0      0     6      1
5          0      0     7      2
6          0      1     1      1
7          0      1     2      6
8          0      1     6      1
9          0      1     6      2
10         0      1     7      3
11         0      2     1      1
12         0      2     2      8
13         0      2    10      2
14         0      2     6      3
15         0      2     6      1
16         0      2     7      1
17         0      3     2     19
18         0      3    10      1
19         0      3     6      4
20         0      3     6      2
21         0      3     7      3
22         0      4     2     16
23         0      4    10      1
24         0      4     6      3
25         0      4     6      2
26         0      4     7      4
27         0      5     1      1
28         0      5     2     30
29         0      5     6      1
...      ...    ...   ...    ...
18133     29    101    10      6
18134     29    101     6     44
18135     29    101     7      5
18136     29    101     6     12
18137     29    101     7     36
18138     29    102     1      1
18139     29    102     2      7
18140     29    102     8      6
18141     29    102     6     12
18142     29    102     6      3
18143     29    102     7      3
18144     29    103     2      5
18145     29    103     8      2
18146     29    103     6      5
18147     29    103     6      3
18148     29    103     7      1
18149     29    104     1      1
18150     29    104     2     12
18151     29    104     8      4
18152     29    104     9      1
18153     29    104     6      9
18154     29    104     6      1
18155     29    104     7     12
18156     29    105     1      4
18157     29    105     2     23
18158     29    105     7      1
18159     29    105     9      2
18160     29    105     6      2
18161     29    105     6      4
18162     29    105     7      9

[18163 rows x 4 columns]

In [14]:
for i in a_part['store'].drop_duplicates():
    a = a_part[lambda a_part : a_part['store'] == i]
    b = a['weeks'].drop_duplicates().count()
    print (i,b)

0 106
2 106
3 106
4 106
5 106
6 106
7 106
8 106
9 106
10 106
11 106
12 106
13 79
14 106
16 106
17 106
18 106
19 106
21 106
22 106
23 106
24 106
25 106
26 92
27 106
28 106
29 106
1 17
15 17
20 29


In [15]:
a0=df[lambda df: df['store'] == 0]
a2=df[lambda df: df['store'] == 2]
a3=df[lambda df: df['store'] == 3]
a4=df[lambda df: df['store'] == 4]
a5=df[lambda df: df['store'] == 5]
a6=df[lambda df: df['store'] == 6]
a7=df[lambda df: df['store'] == 7]
a8=df[lambda df: df['store'] == 8]
a9=df[lambda df: df['store'] == 9]
a10=df[lambda df: df['store'] == 10]
a11=df[lambda df: df['store'] == 11]
a12=df[lambda df: df['store'] == 12]
a14=df[lambda df: df['store'] == 14]
a16=df[lambda df: df['store'] == 16]
a17=df[lambda df: df['store'] == 17]
a18=df[lambda df: df['store'] == 18]
a19=df[lambda df: df['store'] == 19]
a21=df[lambda df: df['store'] == 21]
a22=df[lambda df: df['store'] == 22]
a23=df[lambda df: df['store'] == 23]
a24=df[lambda df: df['store'] == 24]
a25=df[lambda df: df['store'] == 25]
a27=df[lambda df: df['store'] == 27]
a28=df[lambda df: df['store'] == 28]
a29=df[lambda df: df['store'] == 29]
df_n=pd.concat([a0,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a14,a16,a17,a18,a19,a21,a22,a23,a24,a25,a27,a28,a29])
#df_n

In [16]:
df_n['sales']=0
df_n

store  weeks  item  sales
0          0      0     0      0
1          0      0     1      0
2          0      0     2      0
3          0      0     3      0
4          0      0     4      0
5          0      0     5      0
6          0      0     6      0
7          0      0     7      0
8          0      0     8      0
9          0      0     9      0
10         0      0    10      0
11         0      0    11      0
12         0      1     0      0
13         0      1     1      0
14         0      1     2      0
15         0      1     3      0
16         0      1     4      0
17         0      1     5      0
18         0      1     6      0
19         0      1     7      0
20         0      1     8      0
21         0      1     9      0
22         0      1    10      0
23         0      1    11      0
24         0      2     0      0
25         0      2     1      0
26         0      2     2      0
27         0      2     3      0
28         0      2     4      0
29         0      2     5      0
...      ...    ...   ...    ...
38130     29    103     6      0
38131     29    103     7      0
38132     29    103     8      0
38133     29    103     9      0
38134     29    103    10      0
38135     29    103    11      0
38136     29    104     0      0
38137     29    104     1      0
38138     29    104     2      0
38139     29    104     3      0
38140     29    104     4      0
38141     29    104     5      0
38142     29    104     6      0
38143     29    104     7      0
38144     29    104     8      0
38145     29    104     9      0
38146     29    104    10      0
38147     29    104    11      0
38148     29    105     0      0
38149     29    105     1      0
38150     29    105     2      0
38151     29    105     3      0
38152     29    105     4      0
38153     29    105     5      0
38154     29    105     6      0
38155     29    105     7      0
38156     29    105     8      0
38157     29    105     9      0
38158     29    105    10      0
38159     29    105    11      0

[31800 rows x 4 columns]

In [17]:
a0=a_part[lambda a_part: a_part['store'] == 0]
a2=a_part[lambda a_part: a_part['store'] == 2]
a3=a_part[lambda a_part: a_part['store'] == 3]
a4=a_part[lambda a_part: a_part['store'] == 4]
a5=a_part[lambda a_part: a_part['store'] == 5]
a6=a_part[lambda a_part: a_part['store'] == 6]
a7=a_part[lambda a_part: a_part['store'] == 7]
a8=a_part[lambda a_part: a_part['store'] == 8]
a9=a_part[lambda a_part: a_part['store'] == 9]
a10=a_part[lambda a_part: a_part['store'] == 10]
a11=a_part[lambda a_part: a_part['store'] == 11]
a12=a_part[lambda a_part: a_part['store'] == 12]
a14=a_part[lambda a_part: a_part['store'] == 14]
a16=a_part[lambda a_part: a_part['store'] == 16]
a17=a_part[lambda a_part: a_part['store'] == 17]
a18=a_part[lambda a_part: a_part['store'] == 18]
a19=a_part[lambda a_part: a_part['store'] == 19]
a21=a_part[lambda a_part: a_part['store'] == 21]
a22=a_part[lambda a_part: a_part['store'] == 22]
a23=a_part[lambda a_part: a_part['store'] == 23]
a24=a_part[lambda a_part: a_part['store'] == 24]
a25=a_part[lambda a_part: a_part['store'] == 25]
a27=a_part[lambda a_part: a_part['store'] == 27]
a28=a_part[lambda a_part: a_part['store'] == 28]
a29=a_part[lambda a_part: a_part['store'] == 29]
a_p=pd.concat([a0,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a14,a16,a17,a18,a19,a21,a22,a23,a24,a25,a27,a28,a29])
#a_p

In [18]:
a_pn = pd.DataFrame(a_p.groupby(['store','weeks','item']).sum()['sales']).unstack()
a = a_pn.fillna(0)
a_sales = a.stack()

In [19]:
a_salesn = a_sales.reset_index(drop=True)
a_salesn

sales
0        0.0
1        1.0
2       30.0
3        0.0
4        0.0
5        0.0
6        1.0
7        2.0
8        0.0
9        2.0
10       2.0
11       0.0
12       0.0
13       1.0
14       6.0
15       0.0
16       0.0
17       0.0
18       3.0
19       3.0
20       0.0
21       0.0
22       0.0
23       0.0
24       0.0
25       1.0
26       8.0
27       0.0
28       0.0
29       0.0
...      ...
31770    8.0
31771    1.0
31772    2.0
31773    0.0
31774    0.0
31775    0.0
31776    0.0
31777    1.0
31778   12.0
31779    0.0
31780    0.0
31781    0.0
31782   10.0
31783   12.0
31784    4.0
31785    1.0
31786    0.0
31787    0.0
31788    0.0
31789    4.0
31790   23.0
31791    0.0
31792    0.0
31793    0.0
31794    6.0
31795   10.0
31796    0.0
31797    2.0
31798    0.0
31799    0.0

[31800 rows x 1 columns]

In [20]:
df_nf = df_n.reset_index(drop=True)
df_nf['sales'] = a_salesn
df_nf

store  weeks  item  sales
0          0      0     0    0.0
1          0      0     1    1.0
2          0      0     2   30.0
3          0      0     3    0.0
4          0      0     4    0.0
5          0      0     5    0.0
6          0      0     6    1.0
7          0      0     7    2.0
8          0      0     8    0.0
9          0      0     9    2.0
10         0      0    10    2.0
11         0      0    11    0.0
12         0      1     0    0.0
13         0      1     1    1.0
14         0      1     2    6.0
15         0      1     3    0.0
16         0      1     4    0.0
17         0      1     5    0.0
18         0      1     6    3.0
19         0      1     7    3.0
20         0      1     8    0.0
21         0      1     9    0.0
22         0      1    10    0.0
23         0      1    11    0.0
24         0      2     0    0.0
25         0      2     1    1.0
26         0      2     2    8.0
27         0      2     3    0.0
28         0      2     4    0.0
29         0      2     5    0.0
...      ...    ...   ...    ...
31770     29    103     6    8.0
31771     29    103     7    1.0
31772     29    103     8    2.0
31773     29    103     9    0.0
31774     29    103    10    0.0
31775     29    103    11    0.0
31776     29    104     0    0.0
31777     29    104     1    1.0
31778     29    104     2   12.0
31779     29    104     3    0.0
31780     29    104     4    0.0
31781     29    104     5    0.0
31782     29    104     6   10.0
31783     29    104     7   12.0
31784     29    104     8    4.0
31785     29    104     9    1.0
31786     29    104    10    0.0
31787     29    104    11    0.0
31788     29    105     0    0.0
31789     29    105     1    4.0
31790     29    105     2   23.0
31791     29    105     3    0.0
31792     29    105     4    0.0
31793     29    105     5    0.0
31794     29    105     6    6.0
31795     29    105     7   10.0
31796     29    105     8    0.0
31797     29    105     9    2.0
31798     29    105    10    0.0
31799     29    105    11    0.0

[31800 rows x 4 columns]

In [22]:
df_year5t = df[lambda df: df['weeks'] < 53]
df_year5t['years'] = 2015
#df_year5 = df_year5t['years']
#df_year5t

/home/lin/anaconda3/envs/boost/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [23]:
df_year6t = df[lambda df: df['weeks'] > 52]
df_year6t['years'] = 2016
#df_year6 = df_year6t['years']
#df_year6t

/home/lin/anaconda3/envs/boost/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [24]:
df_yearadd = pd.concat([df_year5t,df_year6t])
df = df_yearadd

In [25]:
df['sales'] = np.log1p(df.sales.values)
df.sample(2)

store  weeks  item  sales  years
16492     14    102     4    0.0   2016
22977     22      6     9    0.0   2015

In [26]:
#方法定义
def one_hot_encoder(df, ohe_cols=['store','item','weeks','years']):
    '''
    One-Hot Encoder function
    '''
    print('Creating OHE features..\nOld df shape:{}'.format(df.shape))
    df = pd.get_dummies(df, columns=ohe_cols)
    print('New df shape:{}'.format(df.shape))
    return df

def create_sales_agg_monthwise_features(df, gpby_cols, target_col, agg_funcs):
    '''
    Creates various sales agg features with given agg functions  
    '''
    gpby = df.groupby(gpby_cols)
    newdf = df[gpby_cols].drop_duplicates().reset_index(drop=True)
    for agg_name, agg_func in agg_funcs.items():
        aggdf = gpby[target_col].agg(agg_func).reset_index()
        aggdf.rename(columns={target_col:target_col+'_'+agg_name}, inplace=True)
        newdf = newdf.merge(aggdf, on=gpby_cols, how='left')
    return newdf

# Creating sales lag features
def create_sales_lag_feats(df, gpby_cols, target_col, lags):
    gpby = df.groupby(gpby_cols)
    for i in lags:
        df['_'.join([target_col, 'lag', str(i)])] = \
                gpby[target_col].shift(i).values + np.random.normal(scale=1.6, size=(len(df),))
    return df

# Creating sales rolling mean features
def create_sales_rmean_feats(df, gpby_cols, target_col, windows, min_periods=2, 
                             shift=1, win_type=None):
    gpby = df.groupby(gpby_cols)
    for w in windows:
        df['_'.join([target_col, 'rmean', str(w)])] = \
            gpby[target_col].shift(shift).rolling(window=w, 
                                                  min_periods=min_periods,
                                                  win_type=win_type).mean().values +\
            np.random.normal(scale=1.6, size=(len(df),))
    return df

# Creating sales rolling median features
'''def create_sales_rmed_feats(df, gpby_cols, target_col, windows, min_periods=2, 
                            shift=1, win_type=None):
    gpby = df.groupby(gpby_cols)
    for w in windows:
        df['_'.join([target_col, 'rmed', str(w)])] = \
            gpby[target_col].shift(shift).rolling(window=w, 
                                                  min_periods=min_periods,
                                                  win_type=win_type).median().values +\
            np.random.normal(scale=1.6, size=(len(df),))
    return df
'''

# Creating sales exponentially weighted mean features
def create_sales_ewm_feats(df, gpby_cols, target_col, alpha=[0.9], shift=[1]):
    gpby = df.groupby(gpby_cols)
    for a in alpha:
        for s in shift:
            df['_'.join([target_col, 'lag', str(s), 'ewm', str(a)])] = \
                gpby[target_col].shift(s).ewm(alpha=a).mean().values
    return df


In [27]:
#设置训练数据，验证数据
masked_series = (df['years']==2016) & (df['weeks'].isin([53,54,55]))
masked_series2 = (df['years']==2016) & (~(df['weeks'].isin([53,54,55])))
df.loc[(masked_series), 'train_or_test'] = 'val'
df.loc[(masked_series2), 'train_or_test'] = 'no_train'
print('Train shape: {}'.format(df.loc[df['years']==2015,:].shape))
print('Validation shape: {}'.format(df.loc[df.train_or_test=='val',:].shape))
#print('No train shape: {}'.format(df.loc[df.train_or_test=='no_train',:].shape))
#print('Test shape: {}'.format(df.loc[df['年份']==2016,:].shape))

Train shape: (15900, 6)
Validation shape: (900, 6)


In [45]:
df

store  weeks  item     sales  years train_or_test  sales_lag_3  \
0          0      0     0  0.000000   2015           NaN          NaN   
1          0      0     1  0.693147   2015           NaN          NaN   
2          0      0     2  3.433987   2015           NaN          NaN   
3          0      0     3  0.000000   2015           NaN          NaN   
4          0      0     4  0.000000   2015           NaN          NaN   
5          0      0     5  0.000000   2015           NaN          NaN   
6          0      0     6  0.693147   2015           NaN          NaN   
7          0      0     7  1.098612   2015           NaN          NaN   
8          0      0     8  0.000000   2015           NaN          NaN   
9          0      0     9  1.098612   2015           NaN          NaN   
10         0      0    10  1.098612   2015           NaN          NaN   
11         0      0    11  0.000000   2015           NaN          NaN   
12         0      1     0  0.000000   2015           NaN          NaN   
13         0      1     1  0.693147   2015           NaN          NaN   
14         0      1     2  1.945910   2015           NaN          NaN   
15         0      1     3  0.000000   2015           NaN          NaN   
16         0      1     4  0.000000   2015           NaN          NaN   
17         0      1     5  0.000000   2015           NaN          NaN   
18         0      1     6  1.386294   2015           NaN          NaN   
19         0      1     7  1.386294   2015           NaN          NaN   
20         0      1     8  0.000000   2015           NaN          NaN   
21         0      1     9  0.000000   2015           NaN          NaN   
22         0      1    10  0.000000   2015           NaN          NaN   
23         0      1    11  0.000000   2015           NaN          NaN   
24         0      2     0  0.000000   2015           NaN          NaN   
25         0      2     1  0.693147   2015           NaN          NaN   
26         0      2     2  2.197225   2015           NaN          NaN   
27         0      2     3  0.000000   2015           NaN          NaN   
28         0      2     4  0.000000   2015           NaN          NaN   
29         0      2     5  0.000000   2015           NaN          NaN   
...      ...    ...   ...       ...    ...           ...          ...   
31770     29    103     6  2.197225   2016      no_train     0.132505   
31771     29    103     7  0.693147   2016      no_train     2.197103   
31772     29    103     8  1.098612   2016      no_train     1.158135   
31773     29    103     9  0.000000   2016      no_train     1.459817   
31774     29    103    10  0.000000   2016      no_train     1.220210   
31775     29    103    11  0.000000   2016      no_train     0.976884   
31776     29    104     0  0.000000   2016      no_train    -3.689860   
31777     29    104     1  0.693147   2016      no_train     2.382432   
31778     29    104     2  2.564949   2016      no_train     5.297845   
31779     29    104     3  0.000000   2016      no_train     0.804481   
31780     29    104     4  0.000000   2016      no_train     2.668767   
31781     29    104     5  0.000000   2016      no_train     2.715432   
31782     29    104     6  2.397895   2016      no_train     2.957356   
31783     29    104     7  2.564949   2016      no_train     2.268964   
31784     29    104     8  1.609438   2016      no_train     2.567948   
31785     29    104     9  0.693147   2016      no_train     1.354200   
31786     29    104    10  0.000000   2016      no_train     4.553469   
31787     29    104    11  0.000000   2016      no_train     0.872430   
31788     29    105     0  0.000000   2016      no_train    -2.330638   
31789     29    105     1  1.609438   2016      no_train     0.432444   
31790     29    105     2  3.178054   2016      no_train     0.067476   
31791     29    105     3  0.000000   2016      no_train    -2.457907   
31792     29    105     4  0.000000   2016      no_train    -0.80

In [28]:
df
# Converting sales of validation period to nan so as to resemble test period
train = df
Y_val = train.loc[train.train_or_test=='val', 'sales'].values.reshape((-1))
Y_train = train.loc[train.train_or_test=='train', 'sales'].values.reshape((-1))
train.loc[train.train_or_test=='val', 'sales'] = np.nan
train

store  weeks  item     sales  years train_or_test
0          0      0     0  0.000000   2015           NaN
1          0      0     1  0.693147   2015           NaN
2          0      0     2  3.433987   2015           NaN
3          0      0     3  0.000000   2015           NaN
4          0      0     4  0.000000   2015           NaN
5          0      0     5  0.000000   2015           NaN
6          0      0     6  0.693147   2015           NaN
7          0      0     7  1.098612   2015           NaN
8          0      0     8  0.000000   2015           NaN
9          0      0     9  1.098612   2015           NaN
10         0      0    10  1.098612   2015           NaN
11         0      0    11  0.000000   2015           NaN
12         0      1     0  0.000000   2015           NaN
13         0      1     1  0.693147   2015           NaN
14         0      1     2  1.945910   2015           NaN
15         0      1     3  0.000000   2015           NaN
16         0      1     4  0.000000   2015           NaN
17         0      1     5  0.000000   2015           NaN
18         0      1     6  1.386294   2015           NaN
19         0      1     7  1.386294   2015           NaN
20         0      1     8  0.000000   2015           NaN
21         0      1     9  0.000000   2015           NaN
22         0      1    10  0.000000   2015           NaN
23         0      1    11  0.000000   2015           NaN
24         0      2     0  0.000000   2015           NaN
25         0      2     1  0.693147   2015           NaN
26         0      2     2  2.197225   2015           NaN
27         0      2     3  0.000000   2015           NaN
28         0      2     4  0.000000   2015           NaN
29         0      2     5  0.000000   2015           NaN
...      ...    ...   ...       ...    ...           ...
31770     29    103     6  2.197225   2016      no_train
31771     29    103     7  0.693147   2016      no_train
31772     29    103     8  1.098612   2016      no_train
31773     29    103     9  0.000000   2016      no_train
31774     29    103    10  0.000000   2016      no_train
31775     29    103    11  0.000000   2016      no_train
31776     29    104     0  0.000000   2016      no_train
31777     29    104     1  0.693147   2016      no_train
31778     29    104     2  2.564949   2016      no_train
31779     29    104     3  0.000000   2016      no_train
31780     29    104     4  0.000000   2016      no_train
31781     29    104     5  0.000000   2016      no_train
31782     29    104     6  2.397895   2016      no_train
31783     29    104     7  2.564949   2016      no_train
31784     29    104     8  1.609438   2016      no_train
31785     29    104     9  0.693147   2016      no_train
31786     29    104    10  0.000000   2016      no_train
31787     29    104    11  0.000000   2016      no_train
31788     29    105     0  0.000000   2016      no_train
31789     29    105     1  1.609438   2016      no_train
31790     29    105     2  3.178054   2016      no_train
31791     29    105     3  0.000000   2016      no_train
31792     29    105     4  0.000000   2016      no_train
31793     29    105     5  0.000000   2016      no_train
31794     29    105     6  1.945910   2016      no_train
31795     29    105     7  2.397895   2016      no_train
31796     29    105     8  0.000000   2016      no_train
31797     29    105     9  1.098612   2016      no_train
31798     29    105    10  0.000000   2016      no_train
31799     29    105    11  0.000000   2016      no_train

[31800 rows x 6 columns]

In [29]:
# # Creating sales lag, rolling mean, rolling median, ohe features of the above train set
train = create_sales_lag_feats(train, gpby_cols=['store','item'], target_col='sales', 
                               lags=[3,4,5,6,7,8,9,18,36,53])

train = create_sales_rmean_feats(train, gpby_cols=['store','item'], 
                                 target_col='sales', windows=[18,36], 
                                 min_periods=10, win_type='triang') #98,119,91,182,

train = create_sales_ewm_feats(train, gpby_cols=['store','item'], 
                               target_col='sales', 
                               alpha=[0.95, 0.9, 0.8, 0.7, 0.6, 0.5], 
                               shift=[3,4,5,6,7,8,9,18,36,53])

train = one_hot_encoder(train, ohe_cols=['store','item','weeks','years']) 

val = train.loc[train.train_or_test=='val', :]
train = train.loc[train.train_or_test=='no_train', :]
print('Train shape:{}, Val shape:{}'.format(train.shape, val.shape))

Creating OHE features..
Old df shape:(31800, 78)
New df shape:(31800, 219)
Train shape:(15000, 219), Val shape:(900, 219)


In [31]:
#设置对称的绝对百分比误差
def smape(preds, target):
    '''
    Function to calculate SMAPE
    '''
    n = len(preds)
    masked_arr = ~((preds==0)&(target==0))
    preds, target = preds[masked_arr], target[masked_arr]
    num = np.abs(preds-target)
    denom = np.abs(preds)+np.abs(target)
    smape_val = (200*np.sum(num/denom))/n
    return smape_val

def lgbm_smape(preds, train_data):
    '''
    Custom Evaluation Function for LGBM
    '''
    labels = train_data.get_label()
    smape_val = smape(np.expm1(preds), np.expm1(labels))
    return 'SMAPE', smape_val, False


In [32]:
# LightGBM parameters
lgb_params = {'task':'train', 'boosting_type':'gbdt', 'objective':'regression', 
              'metric': {'mae'}, 'num_leaves': 10, 'learning_rate': 0.02, 
              'feature_fraction': 0.8, 'max_depth': 5, 'verbose': 0, 
              'num_boost_round':300, 'early_stopping_rounds':1, 'nthread':-1}

import lightgbm as lgb
#import time
lgbtrain = lgb.Dataset(data=train.loc[:,cols].values, label=Y_train, 
                       feature_name=cols)
lgbval = lgb.Dataset(data=val.loc[:,cols].values, label=Y_val, 
                     reference=lgbtrain, feature_name=cols)


In [33]:
def lgb_validation(params, lgbtrain, lgbval, X_val, Y_val, verbose_eval):
    #t0 = time.time()
    evals_result = {}
    model = lgb.train(params, lgbtrain, num_boost_round=params['num_boost_round'], 
                      valid_sets=[lgbtrain, lgbval], feval=lgbm_smape, 
                      early_stopping_rounds=params['early_stopping_rounds'], evals_result=evals_result,
                      verbose_eval=verbose_eval)
    print(model.best_iteration)
   #print('Total time taken to build the model: ', (time.time()-t0)/60, 'minutes!!')
    pred_Y_val = model.predict(X_val, num_iteration=model.best_iteration)
    pred_Y_val = np.expm1(pred_Y_val)
    Y_val = np.expm1(Y_val)
    val_df = pd.DataFrame(columns=['true_Y_val','pred_Y_val'])
    val_df['pred_Y_val'] = pred_Y_val
    val_df['true_Y_val'] = Y_val
    print(val_df.shape)
    print(val_df.sample(5))
    print('SMAPE for validation data is:{}'.format(smape(pred_Y_val, Y_val)))
    return model, val_df
#model, val_df = lgb_validation(lgb_params, lgbtrain, lgbval, val.loc[:,cols].values, 
#                              Y_val, verbose_eval=500)